### ISSUE TITLE
Error when removing one edge in test_graph_bipartite

### ISSUE THREAD

**Issue by mariuzka** [luerhard/bokehgraph#10]
Hey,

I just noticed that if you delete one of the lines 126-129 in ./tests/test_graph_create.py, the code raises the following error: `AmbiguousSolution: Disconnected graph: Ambiguous solution for bipartite sets.`.

That is not how it supposed to be, is it?

Beste,
Marius

![image](https://github.com/user-attachments/assets/5315b4b1-b2a5-4d63-b671-69b728d1bc9f)

**Comment by luerhard** [comment]
It is raised by this function: 

https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.bipartite.basic.sets.html#

Once the graph is not fully connected. I have some ideas for workaround but have to try them out first.

**Comment by mariuzka** [comment]
Unfortunately I came across another error. It occured when I removed the node attribute `bipartite` in `test_graph_bipartite()`:

![image](https://github.com/user-attachments/assets/0b153c29-06db-4b08-8d66-c993175591c2)
![image](https://github.com/user-attachments/assets/facd180f-101c-4f35-9d2b-63fcb444ff20)

**Comment by luerhard** [comment]
should be fixed in 0.4.1
