### ISSUE TITLE
Darstellung der Node-Gruppen in bipartiten Netzwerken fixieren

### ISSUE THREAD

**Issue by mariuzka** [luerhard/bokehgraph#11]
Die Darstellung der Nodes als Vierecke und Kreise in bipartiten Netzwerken ist super. Cool wäre aber noch, wenn man festlegen könnte, dass eine Gruppe immer als Viereck und die andere Gruppe immer als Kreise dargestellt wird. Z.B., dass die Nodes mit bipartite=0 immer als Kreise und die Nodes mit bipartite=1 immer als Vierrecke dargestellt werden. Kann von mir aus auch einfach vom Package festgelegt werden, ohne dass man das als User ändern könnte. Das wäre super! :)

**Comment by mariuzka** [comment]
Aktuell werden immer die Nodes, die weniger sind, als Vierecke dargestellt, wenn ich es richtig gesehen habe. :D

**Comment by luerhard** [comment]
Ah, I see. Dann ist es nur eine kleine Änderung. Ich schau mal, wie ich dazu komme und sag dir die Tage Bescheid :)

**Comment by mariuzka** [comment]
Okay mittlerweile erscheint es mir komplett random, wann welche Gruppe wie dargestellt wird ^^
